### ISSUE TITLE
Change API endpoint URL for requesting sensor data

### ISSUE THREAD

**Issue by mattsches** [home-assistant-ecosystem/python-luftdaten#7]
If I understand the documentation at https://github.com/opendata-stuttgart/meta/wiki/APIs correctly, the recommended API endpoint for requesting sensor data should now be https://data.sensor.community/ instead of the original https://api.luftdaten.info/

Since the latter is hardcoded in this library, it should probably be updated/changed. What do you think?

**Comment by fabaff** [comment]
Make sense to change to new URL.

**Comment by linuxlurak** [comment]
Was there another change? I think "https://api.sensor.community/v1/" is the newest URL. This change broke the home assistant luftdaten component too I guess... It's not working  since two weeks or so. Should I open a ticket here https://github.com/home-assistant/core/tree/dev/homeassistant/components/luftdaten ?
